# Generated by Django 6.0.3 on 2026-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Alumno'), ('T', 'Tutor'), ('E', 'Empresa'), ('I', 'Instituto')], default='A', max_length=1),
        ),
    ]
