# Generated by Django 6.0.3 on 2026-03-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_rol'),
        ('institutos', '0002_cursoacademico_alter_instituto_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=9)),
                ('fecha_matriculacion', models.DateField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutos.institutociclo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
