# Generated by Django 6.0.3 on 2026-03-12 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilalumno'),
        ('institutos', '0002_cursoacademico_alter_instituto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilalumno',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='perfilalumno',
            name='fecha_matriculacion',
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='codigo_postal',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='direccion',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='municipio',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='nif',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='pais_nacimiento',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='provincia',
            field=models.CharField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alicante'), ('AL', 'Almería'), ('O', 'Asturias'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('S', 'Cantabria'), ('CS', 'Castellón'), ('CE', 'Ceuta'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Guipúzcoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('IB', 'Islas Baleares'), ('J', 'Jaén'), ('C', 'La Coruña'), ('LO', 'La Rioja'), ('GC', 'Las Palmas'), ('LE', 'León'), ('L', 'Lleida'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('ML', 'Melilla'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('OR', 'Ourense'), ('P', 'Palencia'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Santa Cruz de Tenerife'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valencia'), ('VA', 'Valladolid'), ('BI', 'Vizcaya'), ('ZA', 'Zamora'), ('Z', 'Zaragoza')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutos.ofertaeducativa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alu', 'Alumno'), ('tut', 'Tutor'), ('emp', 'Empresa'), ('tue', 'Empresa'), ('ins', 'Instituto')], default='alu', max_length=3),
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=16)),
                ('tutoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutos.ofertaeducativa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
