# Generated by Django 6.0.3 on 2026-03-12 19:45

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_perfilalumno_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('alu', 'Alumno'), ('tut', 'Tutor'), ('emp', 'Empresa'), ('tue', 'Tutor de Empresa'), ('ins', 'Instituto')], default='alu', max_length=3),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('alu', 'Alumno'), ('tut', 'Tutor'), ('emp', 'Empresa'), ('tue', 'Tutor de Empresa'), ('ins', 'Instituto')], max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
