# Generated by Django 6.0.3 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_rol_invitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('alu', 'Alumno'), ('tut', 'Tutor'), ('emp', 'Empresa'), ('tue', 'Tutor de Empresa'), ('ins', 'Instituto')], max_length=3),
        ),
    ]
