# Generated by Django 6.0.3 on 2026-03-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usuario_rol_alter_invitacion_rol_and_more'),
        ('empresas', '0002_delete_tutorempresa'),
        ('institutos', '0005_institutociclo_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutos.instituto'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='oferta_educativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutos.ofertaeducativa'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='receptor',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
