# Generated by Django 6.0.3 on 2026-03-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('direccion', models.CharField(max_length=256)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutoCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('N', 'Normal'), ('I', 'Intensivo'), ('B', 'Bilingüe')], max_length=1)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos.cicloformativo')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos.instituto')),
            ],
        ),
        migrations.AddField(
            model_name='instituto',
            name='ciclos',
            field=models.ManyToManyField(through='institutos.InstitutoCiclo', to='institutos.cicloformativo'),
        ),
    ]
