# Generated by Django 6.0.3 on 2026-03-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.IntegerField()),
                ('ano_fin', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='instituto',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OfertaEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos.cursoacademico')),
                ('instituto_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutos.institutociclo')),
            ],
        ),
    ]
