# Generated by Django 6.0.3 on 2026-03-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0002_cursoacademico_alter_instituto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituto',
            name='usuario',
        ),
    ]
