# Generated by Django 6.0.3 on 2026-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0003_remove_instituto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='codigo_postal',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='instituto',
            name='municipio',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instituto',
            name='provincia',
            field=models.CharField(choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alicante'), ('AL', 'Almería'), ('O', 'Asturias'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('S', 'Cantabria'), ('CS', 'Castellón'), ('CE', 'Ceuta'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Guipúzcoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('IB', 'Islas Baleares'), ('J', 'Jaén'), ('C', 'La Coruña'), ('LO', 'La Rioja'), ('GC', 'Las Palmas'), ('LE', 'León'), ('L', 'Lleida'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('ML', 'Melilla'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('OR', 'Ourense'), ('P', 'Palencia'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Santa Cruz de Tenerife'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valencia'), ('VA', 'Valladolid'), ('BI', 'Vizcaya'), ('ZA', 'Zamora'), ('Z', 'Zaragoza')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='instituto',
            name='direccion',
            field=models.CharField(default='', max_length=128),
        ),
    ]
