# Generated by Django 6.0.3 on 2026-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0004_instituto_codigo_postal_instituto_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutociclo',
            name='turno',
            field=models.CharField(choices=[('D', 'Diurno'), ('V', 'Vespertino')], default='D', max_length=1),
        ),
    ]
