# Generated by Django 6.0.3 on 2026-03-12 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('codigo_postal', models.CharField(max_length=16)),
                ('municipio', models.CharField(max_length=64)),
                ('provincia', models.CharField(blank=True, choices=[('VI', 'Álava'), ('AB', 'Albacete'), ('A', 'Alicante'), ('AL', 'Almería'), ('O', 'Asturias'), ('AV', 'Ávila'), ('BA', 'Badajoz'), ('B', 'Barcelona'), ('BU', 'Burgos'), ('CC', 'Cáceres'), ('CA', 'Cádiz'), ('S', 'Cantabria'), ('CS', 'Castellón'), ('CE', 'Ceuta'), ('CR', 'Ciudad Real'), ('CO', 'Córdoba'), ('CU', 'Cuenca'), ('GI', 'Girona'), ('GR', 'Granada'), ('GU', 'Guadalajara'), ('SS', 'Guipúzcoa'), ('H', 'Huelva'), ('HU', 'Huesca'), ('IB', 'Islas Baleares'), ('J', 'Jaén'), ('C', 'La Coruña'), ('LO', 'La Rioja'), ('GC', 'Las Palmas'), ('LE', 'León'), ('L', 'Lleida'), ('LU', 'Lugo'), ('M', 'Madrid'), ('MA', 'Málaga'), ('ML', 'Melilla'), ('MU', 'Murcia'), ('NA', 'Navarra'), ('OR', 'Ourense'), ('P', 'Palencia'), ('PO', 'Pontevedra'), ('SA', 'Salamanca'), ('TF', 'Santa Cruz de Tenerife'), ('SG', 'Segovia'), ('SE', 'Sevilla'), ('SO', 'Soria'), ('T', 'Tarragona'), ('TE', 'Teruel'), ('TO', 'Toledo'), ('V', 'Valencia'), ('VA', 'Valladolid'), ('BI', 'Vizcaya'), ('ZA', 'Zamora'), ('Z', 'Zaragoza')], max_length=2)),
                ('pais', models.CharField(max_length=64)),
                ('entidad_juridica', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=128)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('cargo', models.CharField(max_length=64)),
                ('base_normativa', models.TextField()),
                ('efectuado_por', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=16)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
