# Generated by Django 6.0.3 on 2026-03-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorEmpresa',
        ),
    ]
